export const FETCH_RECIPE_LIST_START = 'FETCH_RECIPE_LIST_START';
export const FETCH_RECIPE_LIST_SUCCESS = 'FETCH_RECIPE_LIST_SUCCESS';
export const FETCH_RECIPE_LIST_FAILURE = 'FETCH_RECIPE_LIST_FAILURE';

export const FETCH_RECIPE_DETAILS_START = 'FETCH_RECIPE_DETAILS_START';
export const FETCH_RECIPE_DETAILS_SUCCESS = 'FETCH_RECIPE_DETAILS_SUCCESS';
export const FETCH_RECIPE_DETAILS_FAILURE = 'FETCH_RECIPE_DETAILS_FAILURE';

export const SET_CURRENTLY_SELECTED_RECIPE = 'SET_CURRENTLY_SELECTED_RECIPE';
